
export const topicGroups = [
  {
    section: "CSS Tutorial",
    items: [
      { id: "css-home", title: "CSS Home" },
      { id: "css-intro", title: "CSS Introduction" },
      { id: "css-syntax", title: "CSS Syntax" },
      { id: "css-selectors", title: "CSS Selectors" },
      { id: "css-comments", title: "CSS Comments" },
      { id: "css-colors", title: "CSS Colors" },
      { id: "css-backgrounds", title: "CSS Backgrounds" },
      { id: "css-borders", title: "CSS Borders" },
      { id: "css-margins", title: "CSS Margins" },
      { id: "css-padding", title: "CSS Padding" },
      { id: "css-height-width", title: "CSS Height/Width" },
      { id: "css-box-model", title: "CSS Box Model" },
      { id: "css-outline", title: "CSS Outline" },
      { id: "css-text", title: "CSS Text" },
      { id: "css-fonts", title: "CSS Fonts" },
      { id: "css-icons", title: "CSS Icons" },
      { id: "css-links", title: "CSS Links" },
      { id: "css-lists", title: "CSS Lists" },
      { id: "css-tables", title: "CSS Tables" },
      { id: "css-display", title: "CSS Display" },
      { id: "css-max-width", title: "CSS Max-width" },
      { id: "css-position", title: "CSS Position" },
      { id: "css-z-index", title: "CSS Z-Index" },
      { id: "css-overflow", title: "CSS Overflow" },
      { id: "css-float", title: "CSS Float" },
      { id: "css-inline-block", title: "CSS Inline-Block" },
      { id: "css-align", title: "CSS Align" },
      { id: "css-combinators", title: "CSS Combinators" },
      { id: "css-pseudo-class", title: "CSS Pseudo-classes" },
      { id: "css-pseudo-element", title: "CSS Pseudo-elements" },
      { id: "css-opacity", title: "CSS Opacity" },
      { id: "css-navigation-bar", title: "CSS Navigation Bar" },
      { id: "css-dropdowns", title: "CSS Dropdowns" },
      { id: "css-image-gallery", title: "CSS Image Gallery" },
    ],
  },
  {
    section: "CSS Advanced",
    items: [
      { id: "css-rounded-corners", title: "CSS Rounded Corners" },
      { id: "css-border-images", title: "CSS Border Images" },
      { id: "css-backgrounds-advanced", title: "CSS Multiple Backgrounds" },
      { id: "css-gradients", title: "CSS Gradients" },
      { id: "css-shadows", title: "CSS Shadows" },
      { id: "css-text-effects", title: "CSS Text Effects" },
      { id: "css-web-fonts", title: "CSS Web Fonts" },
      { id: "css-2d-transforms", title: "CSS 2D Transforms" },
      { id: "css-3d-transforms", title: "CSS 3D Transforms" },
      { id: "css-transitions", title: "CSS Transitions" },
      { id: "css-animations", title: "CSS Animations" },
      { id: "css-tool-tips", title: "CSS Tooltips" },
      { id: "css-style-images", title: "CSS Style Images" },
      { id: "css-object-fit", title: "CSS Object-fit" },
    ],
  },
  {
    section: "CSS Responsive",
    items: [
      { id: "css-responsive", title: "CSS Responsive Web Design" },
      { id: "css-rwd-intro", title: "RWD Introduction" },
      { id: "css-rwd-viewport", title: "RWD Viewport" },
      { id: "css-media-queries", title: "CSS Media Queries" },
      { id: "css-grid-view", title: "CSS Grid View" },
      { id: "css-flexbox", title: "CSS Flexbox" },
    ],
  },
  {
    section: "CSS Grid",
    items: [
      { id: "css-grid", title: "CSS Grid Layout" },
      { id: "css-grid-intro", title: "CSS Grid Introduction" },
      { id: "css-grid-container", title: "CSS Grid Container" },
      { id: "css-grid-item", title: "CSS Grid Item" },
    ],
  },
  {
    section: "CSS SASS",
    items: [
      { id: "css-sass", title: "CSS SASS" },
      { id: "css-sass-syntax", title: "SASS Syntax" },
      { id: "css-sass-variables", title: "SASS Variables" },
      { id: "css-sass-nesting", title: "SASS Nesting" },
      { id: "css-sass-mixins", title: "SASS Mixins" },
    ],
  },
];