export const topicGroups = [
  {
    section: "HTML Tutorial",
    items: [
      { id: "html-intro", title: "HTML Introduction" },
      { id: "html-editors", title: "HTML Editors" },
      { id: "html-basic", title: "HTML Basic" },
      { id: "html-elements", title: "HTML Elements" },
      { id: "html-attributes", title: "HTML Attributes" },
      { id: "html-headings", title: "HTML Headings" },
      { id: "html-paragraphs", title: "HTML Paragraphs" },
      { id: "html-styles", title: "HTML Styles" },
      { id: "html-formatting", title: "HTML Formatting" },
      { id: "html-quotations", title: "HTML Quotations" },
      { id: "html-comments", title: "HTML Comments" },
      { id: "html-colors", title: "HTML Colors" },
      { id: "html-css", title: "HTML CSS" },
      { id: "html-links", title: "HTML Links" },
      { id: "html-images", title: "HTML Images" },
      { id: "html-favicon", title: "HTML Favicon" },
      { id: "html-title", title: "HTML Page Title" },
      { id: "html-tables", title: "HTML Tables" },
      { id: "html-lists", title: "HTML Lists" },
      { id: "html-block-inline", title: "HTML Block & Inline" },
      { id: "html-div", title: "HTML Div" },
      { id: "html-classes", title: "HTML Classes" },
      { id: "html-id", title: "HTML Id" },
      { id: "html-iframes", title: "HTML Iframes" },
      { id: "html-javascript", title: "HTML JavaScript" },
      { id: "html-file-paths", title: "HTML File Paths" },
      { id: "html-head", title: "HTML Head" },
      { id: "html-layout", title: "HTML Layout" },
      { id: "html-responsive", title: "HTML Responsive" },
      { id: "html-code", title: "HTML Computercode" },
      { id: "html-semantics", title: "HTML Semantics" },
      { id: "html-guide", title: "HTML Style Guide" },
      { id: "html-entities", title: "HTML Entities" },
      { id: "html-symbols", title: "HTML Symbols" },
      { id: "html-emojis", title: "HTML Emojis" },
      { id: "html-charsets", title: "HTML Charsets" },
      { id: "html-url", title: "HTML URL Encode" },
      { id: "html-xhtml", title: "HTML vs. XHTML" },
    ],
  },
  {
    section: "HTML Forms",
    items: [
      { id: "html-forms", title: "HTML Forms" },
      { id: "html-form-attributes", title: "HTML Form Attributes" },
      { id: "html-form-elements", title: "HTML Form Elements" },
      { id: "html-input-types", title: "HTML Input Types" },
      { id: "html-input-attributes", title: "HTML Input Attributes" },
      { id: "html-input-form-attributes", title: "Input Form Attributes" },
    ],
  },
  {
    section: "HTML Graphics",
    items: [
      { id: "html-canvas", title: "HTML Canvas" },
      { id: "html-svg", title: "HTML SVG" },
    ],
  },
  {
    section: "HTML Media",
    items: [
      { id: "html-media", title: "HTML Media" },
      { id: "html-video", title: "HTML Video" },
      { id: "html-audio", title: "HTML Audio" },
      { id: "html-plugins", title: "HTML Plug-ins" },
      { id: "html-youtube", title: "HTML YouTube" },
    ],
  },
  {
    section: "HTML APIs",
    items: [
      { id: "html-web-api", title: "HTML Web APIs" },
      { id: "html-geolocation", title: "HTML Geolocation" },
      { id: "html-drag-drop", title: "HTML Drag and Drop" },
      { id: "html-storage", title: "HTML Web Storage" },
      { id: "html-workers", title: "HTML Web Workers" },
      { id: "html-sse", title: "HTML SSE" },
    ],
  },
];
