export const topicGroups = [
  {
    section: "JavaScript Tutorial",
    items: [
      { id: "js-home", title: "JavaScript Home" },
      { id: "js-intro", title: "JavaScript Introduction" },
      { id: "js-get-started", title: "JavaScript Get Started" },
      { id: "js-where-to", title: "JavaScript Where To" },
      { id: "js-output", title: "JavaScript Output" },
      { id: "js-statements", title: "JavaScript Statements" },
      { id: "js-syntax", title: "JavaScript Syntax" },
      { id: "js-comments", title: "JavaScript Comments" },
      { id: "js-variables", title: "JavaScript Variables" },
      { id: "js-let", title: "JavaScript Let" },
      { id: "js-const", title: "JavaScript Const" },
      { id: "js-operators", title: "JavaScript Operators" },
      { id: "js-arithmetic", title: "JavaScript Arithmetic" },
      { id: "js-assignment", title: "JavaScript Assignment" },
      { id: "js-data-types", title: "JavaScript Data Types" },
      { id: "js-functions", title: "JavaScript Functions" },
      { id: "js-objects", title: "JavaScript Objects" },
      { id: "js-events", title: "JavaScript Events" },
      { id: "js-strings", title: "JavaScript Strings" },
      { id: "js-string-methods", title: "JavaScript String Methods" },
      { id: "js-numbers", title: "JavaScript Numbers" },
      { id: "js-number-methods", title: "JavaScript Number Methods" },
      { id: "js-arrays", title: "JavaScript Arrays" },
      { id: "js-array-methods", title: "JavaScript Array Methods" },
      { id: "js-dates", title: "JavaScript Dates" },
      { id: "js-date-formats", title: "JavaScript Date Formats" },
      { id: "js-math", title: "JavaScript Math" },
      { id: "js-if-else", title: "JavaScript If...Else" },
      { id: "js-switch", title: "JavaScript Switch" },
      { id: "js-loop-for", title: "JavaScript For Loop" },
      { id: "js-loop-while", title: "JavaScript While Loop" },
      { id: "js-break-continue", title: "JavaScript Break/Continue" },
    ],
  },
  {
    section: "JavaScript Advanced",
    items: [
      { id: "js-iterables", title: "JavaScript Iterables" },
      { id: "js-sets", title: "JavaScript Sets" },
      { id: "js-maps", title: "JavaScript Maps" },
      { id: "js-typeof", title: "JavaScript typeof" },
      { id: "js-type-conversion", title: "JavaScript Type Conversion" },
      { id: "js-bitwise", title: "JavaScript Bitwise" },
      { id: "js-regexp", title: "JavaScript Regular Expressions" },
      { id: "js-errors", title: "JavaScript Errors" },
      { id: "js-scope", title: "JavaScript Scope" },
      { id: "js-hoisting", title: "JavaScript Hoisting" },
      { id: "js-strict-mode", title: "JavaScript Strict Mode" },
      { id: "js-this", title: "JavaScript this Keyword" },
      { id: "js-arrow-function", title: "JavaScript Arrow Functions" },
      { id: "js-classes", title: "JavaScript Classes" },
      { id: "js-modules", title: "JavaScript Modules" },
      { id: "js-json", title: "JavaScript JSON" },
    ],
  },
  {
    section: "JavaScript DOM",
    items: [
      { id: "js-dom-intro", title: "JavaScript DOM Introduction" },
      { id: "js-dom-methods", title: "JavaScript DOM Methods" },
      { id: "js-dom-document", title: "JavaScript DOM Document" },
      { id: "js-dom-elements", title: "JavaScript DOM Elements" },
      { id: "js-dom-html", title: "JavaScript DOM HTML" },
      { id: "js-dom-css", title: "JavaScript DOM CSS" },
      { id: "js-dom-events", title: "JavaScript DOM Events" },
      { id: "js-dom-event-listeners", title: "JavaScript DOM Event Listeners" },
      { id: "js-dom-nodes", title: "JavaScript DOM Nodes" },
      { id: "js-dom-navigation", title: "JavaScript DOM Navigation" },
      { id: "js-dom-collections", title: "JavaScript DOM Collections" },
    ],
  },
  {
    section: "JavaScript BOM",
    items: [
      { id: "js-bom", title: "JavaScript BOM" },
      { id: "js-bom-window", title: "JavaScript Window" },
      { id: "js-bom-screen", title: "JavaScript Screen" },
      { id: "js-bom-location", title: "JavaScript Location" },
      { id: "js-bom-history", title: "JavaScript History" },
      { id: "js-bom-navigator", title: "JavaScript Navigator" },
      { id: "js-bom-dialogs", title: "JavaScript Dialogs" },
      { id: "js-bom-timing", title: "JavaScript Timing" },
    ],
  },
  {
    section: "JavaScript APIs",
    items: [
      { id: "js-api-intro", title: "JavaScript API Introduction" },
      { id: "js-api-web-storage", title: "JavaScript Web Storage" },
      { id: "js-api-fetch", title: "JavaScript Fetch API" },
      { id: "js-api-geolocation", title: "JavaScript Geolocation API" },
      { id: "js-api-canvas", title: "JavaScript Canvas API" },
    ],
  },
];
